### PR TITLE
fixed eclipse error: Plugin execution not covered by lifecycle configuration

### PR DESCRIPTION
**Pull request by pmcgleenon**
Eclipse gives a plugin lifecycle error which is fixed by this change

http://stackoverflow.com/questions/6352208/how-to-solve-plugin-execution-not-covered-by-lifecycle-configuration-for-sprin

Using eclipse STS v3.8.1

### CODE REVIEW

**Comment by deruelle** [comment]
hi @pmcgleenon, thanks for the pull requests ! Would you mind signing the Contributor License Agreement at https://telestax.com/open-source/#Contribute so we can accept them ?

**Comment by pmcgleenon** [comment]
hi, I've done that now.  thanks

**Comment by deruelle** [comment]
Thanks @pmcgleenon . @brainslog can you review ?

**Comment by brainslog** [comment]
Thanks @pmcgleenon for fixing those maven issues. I'd just wish that `example1-1.7.0-SNAPSHOT-jar-with-dependencies.jar` would not have the version qualifier, otherwise we'll need (and likely forget) to change it after each release. But that can be dealt with later. Merging, thanks.

**Comment by deruelle** [comment]
Thanks @pmcgleenon Contribution acknowledged at https://telestax.com/acknowledgements/

**Pull request merged**
