### PR TITLE
netty implementation of tcp and tls transports

### PR DESCRIPTION
**Pull request by jehanzebqayyum**
tcp trasnport migrated to netty.
all tests passed except StackReConnectionTest some of which are failing

### CODE REVIEW

**Comment by brainslog** [comment]
@jehanzebqayyum, thanks for the Pull Request!

I think it'd be more wise to keep the NIO as an alternative, so we should not replace these files but add Netty version(s), and then it can be configured to use any of them. When we feel confident and all tests are passing we should make netty the default.

Also, don't use tabs for indentation, we use 2-space (soon to be checked by checkstyle), so if you can fix that, would be good. Keeping same indentation is always a good practice as it highlights the changes which makes reviewing much easier.

Regarding your question about thread pool, we should re-use as much of the old behavior as possible, so use the concurrent factory. We can revisit this in the future, in a separate issues, weighting the pros and cons of such changes when it's already in a functional state.

I will review this in a more functional way (further testing) and check the code at more depth and comment shortly. Meanwhile feel free to adjust the PR accordingly to the comments.

**Comment by deruelle** [comment]
@brainslog @jehanzebqayyum just committed some new work 2 days ago, feel free to review again.

**Comment by brainslog** [comment]
@jehanzebqayyum, I have performed a few functional tests and it seems there's some issue with netty transport because after *exactly* 1000 messages exchanged, it starts failing with exceptions about wrong version and data length, eg:

```
io.netty.handler.codec.DecoderException: org.jdiameter.api.AvpDataException: java.lang.Exception: Wrong length of data: 280
io.netty.handler.codec.DecoderException: org.jdiameter.api.AvpDataException: java.lang.Exception: Illegal value of version 111
io.netty.handler.codec.DecoderException: org.jdiameter.api.AvpDataException: java.lang.Exception: Illegal value of version 110
io.netty.handler.codec.DecoderException: org.jdiameter.api.AvpDataException: java.lang.Exception: Illegal value of version 98
io.netty.handler.codec.DecoderException: org.jdiameter.api.AvpDataException: java.lang.Exception: Illegal value of version 116
io.netty.handler.codec.DecoderException: org.jdiameter.api.AvpDataException: java.lang.Exception: Illegal value of version 0
```

As you fix that, I'd ask you for a few generic enhancements to this pull request:

- Please squash the commits into a single, so that there are no "unnecessary" changes to some files (like the original NIO TCP* files, which were totally re-written in first commit);
- Use 2 space indentation in the files instead of tab indentation, soon we will add style check and that is the used format; also, never commit re-formatting existing and unchanged code;
- In all new files, use only the TeleStax license header, as in https://github.com/RestComm/jdiameter/blob/8ca3f1b0e67cb0739a39ab1427384ab56d4570fb/core/jdiameter/impl/src/main/java/org/jdiameter/server/impl/app/s13/Event.java#L1-L19

Thanks!

**Comment by jehanzebqayyum** [comment]
Hi @brainslog which test case you run? I think it may be the issue in
converting netty ByteBuf to nio ByteBuffer. I will rather convert the
ByteBuf to byte[].


I will squash commits into single and also include the license in new files.

I actually used the formatter file for eclipse from telestax site. I will
update it 2 space indentation.

**Comment by deruelle** [comment]
@brainslog can you review ?

**Comment by brainslog** [comment]
@jehanzebqayyum, have you been able to replicate the issue with the 1000 requests limit ?

Also, let me know if you will address the comments I've made above (squash into a single commit; fix license headers — some new  files are missing any header and the others have both the TeleStax and JBoss one, please use only the TeleStax one as in the file I've linked; correct indentation — still some files with tab indentation and *core/jdiameter/impl/src/main/java/org/jdiameter/client/impl/parser/MessageParser.java* shows as fully changed, if you can check what's wrong.. maybe line endings ?)

I'm OK with merging even if the 1000 msgs issue is present, we can address it separately, as this change is not impacting the stack core as NIO is still present and default.

Also do you have any TLS tests you can add and/or config you can attach here so I can test it quickly ?

**Comment by jehanzebqayyum** [comment]
The issue for 1000 requests is fixed by changes in MessageParser.

I have few test cases for TLS that i will push.

Once i push the final changes i will take cafe of other things i.e.
license, indents etc

**Comment by brainslog** [comment]
@jehanzebqayyum I have done functional tests and the 1000 requests issue doesn't seem to be totally gone. Now after a "random" number of calls (got it after 453, 1206 and 291 requests). It fails with the following exception:

```
2016-06-25 15:43:10,752 DEBUG PeerImpl - internalError 
org.jdiameter.client.api.io.TransportException: Avp Data Exception:
	at org.jdiameter.client.impl.transport.tcp.netty.TCPClientConnection.onEvent(TCPClientConnection.java:285)
	at org.jdiameter.client.impl.transport.tcp.netty.TCPClientConnection.onAvpDataException(TCPClientConnection.java:247)
	at org.jdiameter.client.impl.transport.tcp.netty.DiameterMessageDecoder.decode(DiameterMessageDecoder.java:81)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jdiameter.api.AvpDataException: java.lang.Exception: Wrong length of data: 276
	at org.jdiameter.client.impl.parser.MessageParser.createMessage(MessageParser.java:121)
	at org.jdiameter.client.impl.transport.tcp.netty.DiameterMessageDecoder.decode(DiameterMessageDecoder.java:79)
	... 16 more
Caused by: java.lang.Exception: Wrong length of data: 276
	at org.jdiameter.client.impl.parser.MessageParser.createMessage(MessageParser.java:103)
	... 17 more
```

Also, now it fails with concurrent calls (with the same exception, might be what causes the above issue) so if I set the call rate in seagull just to 2 calls/s all calls start failing.

**Comment by jehanzebqayyum** [comment]
It seems that netty is reusing bytebuf across multiple messages and in case
of simultaneous calls the way i am reading bytes from bytebuff is causing
this issue. So i should change below code in DiameterMessageDecoder:

​byte[] bytes = new byte[in.readableBytes()];

TO

​byte[] bytes = new byte[messageLength];

in.readBytes(bytes);
....
​
​This will make sure that only bytes of current message are read from the
common bytebuf and not the all available bytes.​

​I will perform some tests on it. Since i cannot make seagul work in
windows, i have to simulate my own.
​

**Comment by deruelle** [comment]
@jehanzebqayyum Thanks! Did you try running a Linux VM to be able to use seagull or setup the thing on an AWS instance, that may speed things up?

**Comment by brainslog** [comment]
@jehanzebqayyum, seagull has a windows binary distribution, what is it that fails for you ?

Regarding the commits, some files are still showing as fully rewritten (IMessageParser.java, MessageParser.java and TLSClientConnection.java - this last one doesn't even seem to have any non-whitespace change), it should be the line endings that you are modifying, please try to fix this so the files show the actual changes and not fully rewritten, which is easier to review.

Also, would be good if you'd squash all the commits into a single one so that the initial changes that you have made on NIO TCP files aren't applied and reverted back. Here are the instructions in how to do it: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits. Let me know if you need help with that. After squashing you'll need to force-push the branch, as it is a new commit history, diverging from the one on the remote branch.

**Comment by deruelle** [comment]
@jehanzebqayyum does the new commit means it's ready to be tested again ?

**Comment by jehanzebqayyum** [comment]
Yes but i am trying to setup a test using seagull which i have failed
initially on windows with error Unable to open log file error in seagull

https://sourceforge.net/p/gull/mailman/message/28322120/


​

**Comment by brainslog** [comment]
@jehanzebqayyum thanks for merging the commits and cleaning things up, it's now much easier to see what has changed and review. Will test later today how it behaves with concurrent requests.

Regarding seagull, make sure that the folder where logs are stored actually exist and that the path is correct. If you are running the scenario from https://github.com/RestComm/jdiameter/tree/master/testsuite/load/core/diameter-env you'll need to create the "logs" folder (git doesn't add it as it is empty, I'll fix that so that it will be ready to run). So, in summary, to run from there:

1. Create the "logs" folder at the same level as "config", "run" and "scenario".
2. From the run folder, run one of the scenarios

Hope it helps.

**Comment by brainslog** [comment]
@jehanzebqayyum, I've tested and it looks much better now, it handles multiple concurrent requests and for long duration. The performance is not yet on a par with NIO TCP (it's only stable up to about 2000 req/s, under the same conditions with NIO I can get ~9000 req/s) but I think it's good enough for now and we can improve on it later.

Will merge, thanks for this great contribution.

**Comment by deruelle** [comment]
@jehanzebqayyum can you sign the contributor license agreement at https://telestax.com/open-source/#Contribute so we can acknowledge you at https://telestax.com/acknowledgements/ ?

@jehanzebqayyum do you think we can try to work on getting netty performance on par or better than the current NIO TCP ?

**Comment by jehanzebqayyum** [comment]
yes sure, you will create a new issue?


Best Regards,
Jehanzeb Qayyum
+971 52 898 2285
+92 3311337064

**Comment by deruelle** [comment]
@jehanzebqayyum Thanks. Acknowledged at https://telestax.com/acknowledgements/. New issue see https://github.com/RestComm/jdiameter/issues/47. Also let's try to finalize the original issue https://github.com/RestComm/jdiameter/issues/35, with adding Netty SCTP too. Thanks !

**Pull request merged**
