### PR TITLE
Fix hang when decodeAvpSet receives vendorId=0

### LINKED ISSUE #86: ElementParser.decodeAvpSet hangs when vendor=0
Hello colleagues,

We are facing an error when we try to decode a message with vendorId AVP=0, which hangs our thread that is using jdiameter.

I think that put a vendorId=0 is illegal, at least in 3GPP specs, but we are receiving traffic with it.

In the [ElementParser](https://github.com/RestComm/jdiameter/blob/master/core/jdiameter/impl/src/main/java/org/jdiameter/client/impl/parser/ElementParser.java) class, method decodeAvpSet(byte[] buffer, int shift):
```
      long vendor = 0;
      if ((flags & 0x80) != 0) {
        vendor = in.readInt();
      }
      // Determine body L = length - 4(code) -1(flags) -3(length) [-4(vendor)]
      byte[] rawData = new byte[length - (8 + (vendor == 0 ? 0 : 4))];
      in.read(rawData);
      // skip remaining.
      // TODO: Do we need to padd everything? Or on send stack should properly fill byte[] ... ?
      if (length % 4 != 0) {
        for (int i; length % 4 != 0; length += i) {
          i = (int) in.skip((4 - length % 4));
        }
      }
```

The code is assuming that vendor=0 means there is no a vendorId AVP, but there is it in fact, so the rawData[] length is 4 bytes bigger than it really is, because vendorId=0 AVP is not removed. This situation triggers a hang in the running thread.

I think this case could be controlled with a simple boolean variable.

Here my fix goes:

```
      long vendor = 0;
      boolean hasVendor = false;
      if ((flags & 0x80) != 0) {
        vendor = in.readInt();
        hasVendor = true;
      }
      // Determine body L = length - 4(code) -1(flags) -3(length) [-4(vendor)]
      byte[] rawData = new byte[length - (8 + (hasVendor ? 4 : 0))];
      in.read(rawData);
      // skip remaining.
      // TODO: Do we need to padd everything? Or on send stack should properly fill byte[] ... ?
      if (length % 4 != 0) {
        for (int i; length % 4 != 0; length += i) {
          i = (int) in.skip((4 - length % 4));
        }
      }
```

### PR DESCRIPTION
**Pull request by jochettino**
I added a boolean variable to control the presence of vendor-id AVP, even if it is vendorId = 0.

Closes #86

### CODE REVIEW

**Comment by deruelle** [comment]
Thanks @jochettino for the contribution ! 
Can you please sign the Contributor License Agreement at https://telestax.com/open-source/#Contribute so we can accept the contribution ?

**Comment by jochettino** [comment]
@deruelle, done!

**Comment by deruelle** [comment]
Thanks @jochettino. @brainslog can you please review ?

**Comment by brainslog** [comment]
Thanks for the nice catch, @jochettino! You are right, a vendor id of zero MUST NOT be used, as per RFC 6733:

```
A Vendor-ID value of zero (0) corresponds to the IETF-adopted AVP
values, as managed by IANA.  Since the absence of the Vendor-ID
field implies that the AVP in question is not vendor specific,
implementations MUST NOT use the value of zero (0) for the
Vendor-ID field.
```

Anyway, we should protect against that, so thanks for the fix! Merging.

I will also add a regression test for this fix, feel free to include one next time ;)

**Pull request merged**
