### PR TITLE
fix nullpointer when get experimental result code avp

### PR DESCRIPTION
**Pull request by seasonsluo**

### CODE REVIEW

**Comment by brainslog** [comment]
Thanks for the contribution @seasonsluo. It seems a valid fix to me, but the title of the Pull Request is misleading, at least in my tests I don't have any NPE.

What I see is that (when no Result-Code AVP is present) even when the Experimental-Result-Code AVP is present, with current code it is never retrieved (null is returned), and with your fix it returns properly.

Is this the same you see ? If so, the fix is good and can be merged.

**Comment by deruelle** [comment]
@seasonsluo any news on your side ?

**Comment by brainslog** [comment]
I'm merging it as it solves a valid problem. Any further issues please open a new issue.

**Comment by deruelle** [comment]
@seasonsluo can you sign the CLA at https://telestax.com/open-source/#Contribute ?

**Pull request merged**
