### PR TITLE
LTE Positioning - SLh & SLg interfaces

### PR DESCRIPTION
**Pull request by ajitlakhwani**

### CODE REVIEW

**Comment by deruelle** [comment]
Thanks @ajitlakhwani. Can you sign the contributor license agreement at http://www.telestax.com/open-source/#Contribute ?
@brainslog @FerUy can you review ?

**Comment by FerUy** [comment]
Of course @deruelle 
@ajitlakhwani seems we've been working in parallel in the same stuff (PR #48 and issues #37 and #38?). Please, feel free to contact me to join efforts and sync (maybe it can help you in resolving remaining conflicts). @brainslog, any further thoughts?

**Comment by ajitlakhwani** [comment]
@deruelle I have signed the contributor license
@FerUy Yes, we should work together for SLh/SLg implementation. I will contact you. Thanks

**Comment by FerUy** [comment]
@ajitlakhwani we are closing this PR as it's colliding with work done and completed with no conflicts in #48 (which also has it's RA almost completed in Jain.Slee/diameter, as can be seen here: https://github.com/RestComm/jain-slee.diameter/issues/15 and here: https://github.com/RestComm/jain-slee.diameter/issues/16). 
As we agreed, can you please focus on #61? By the way, any update on this work? How is it going? Please feel free to reach me out for syncing.

**Pull request closed without merging**
