### PR TITLE
Fix multiple timeout events at the same time

### PR DESCRIPTION
**Pull request by seasonsluo**
Add lock to avoid the client to send timeout events in 2 fsm threads

### CODE REVIEW

**Comment by seasonsluo** [comment]
There are 2 commits:
1. For multiple timeout events issue
2. For fix #28

**Comment by seasonsluo** [comment]
added 2 more commits:
3. Fix sh app callbacks to get requests
4. Fix exception when start up with big traffic

**Comment by deruelle** [comment]
@brainslog please review

**Comment by brainslog** [comment]
Merged. Thanks @seasonsluo.

**Pull request merged**
