### PR TITLE
Modify/fix LCS-Supported-GAD-Shapes AVP type to Unsigned32

### PR DESCRIPTION
**Pull request by FerUy**
This pull request solves issue #126.

### CODE REVIEW

**Comment by FerUy** [comment]
As agreed with @ammendonca, it seems that Unsigned32 specified in 3GPP spec is incorrect, and the type of AVP is indeed Enumerated. Hence, closing this pull request.

**Comment by gsaslis** [comment]
@FerUy 

> specified in 3GPP spec is incorrect
i'm sure you know best, but the way you worded that here might cause some confusion to someone stumbling upon it. 

Does the spec really have some mistake / inaccuracy ? Or is it just common practice to go against the spec?

**Comment by FerUy** [comment]
@gsaslis you're right, the explanation was not very fortunate from my side. This is how it is defined in the 3GPP TS 29.172:

image

It makes no sense how it is defined for an Unsigned32, that's how 3GPP specifies an Enumerated AVP. So, we believe there's a mistake there, and instead of *Unsigned32* it should say *Enumerated*.

So, yes, we believe there's a mistake, and no, it's not a common practice and we **never** go against the spec. This is a special case in which is evident 3GPP has an errata in 3GPP TS 29.172 version 14.1.0 (latest).

**Comment by FerUy** [comment]
Ooops... re-reading the what I posted previously, we just noted that the spec is correct, it's a bitmask and not an enumeration, thus setting bit 0 supports ellipsoidPoint, setting bit 1 supports ellipsoidPointWithUncertainityCircle, etc.

Reopening it...

**Comment by ammendonca** [comment]
Looks good @FerUy ! Thanks

**Comment by FerUy** [comment]
Great @ammendonca 👍

**Pull request merged**
