### PR TITLE
LTE Location Services: SLh and SLg interfaces implementation

### PR DESCRIPTION
**Pull request by FerUy**
This is a pull request for issues #37 and #38, concerning AVP definition and configuration for LTE location services. Complete interface implementation will follow after this peer review.

### CODE REVIEW

**Comment by FerUy** [comment]
Find attached the 3GPP specs versions used for this work. 
Diameter base protocol considered was according to its latest version, i.e. IETF RFC 6733.

[3GPP TS 29.173 v13.0.0 - Location Services (LCS); Diameter-based SLh interface for Control Plane LCS -20151221.docx](https://github.com/RestComm/jdiameter/files/363115/3GPP.TS.29.173.v13.0.0.-.Location.Services.LCS.Diameter-based.SLh.interface.for.Control.Plane.LCS.-20151221.docx)
[3GPP TS 29.172 v13.0.0 - Location Services (LCS); Evolved Packet Core (EPC) LCS Protocol (ELP) between the GMLC and the Mobile Management Entity (MME); SLg interface -20151211.docx](https://github.com/RestComm/jdiameter/files/363114/3GPP.TS.29.172.v13.0.0.-.Location.Services.LCS.Evolved.Packet.Core.EPC.LCS.Protocol.ELP.between.the.GMLC.and.the.Mobile.Management.Entity.MME.SLg.interface.-20151211.docx)

**Comment by deruelle** [comment]
Thanks @FerUy. @brainslog can you review ?

**Comment by FerUy** [comment]
@brainslog, as agreed today with @deruelle, I pushed this commit after working on these issues on a very long flight back home after a business trip. 

It's more about saving all the work than asking for peer review at this time, as some few errors and TODOs are pending in a couple of files (as well as whole testsuite and core/jdiameter-ha/... needed files). Therefore, coming back to the initial plan and changing the one commented at the time of the PR one week ago. In other words, now going for the full implementation in this PR. 

So, again, I pushed this work more for storing matters than for peer reviewing, as still there's some work to do and having other related priorities (also, now the branch has conflicts with master it didn't have 6 days ago)... but we are 5000+ lines of code and 53 files closer than we were yesterday ;)

**Comment by brainslog** [comment]
@FerUy, thanks for this Pull Request. Not reviewing the content itself yet, as you say it is still a WIP, but I'd ask you not to modify what hasn't been really modified, like whitespace changes, etc. As can be seen in the first commit, the Avp.java has been totally re-written (and although second commit says it tries to fix it, it's still the same).

Also, previously we had some mixed indentation, with 2, 4 spaces and at some places even with tabs and now I've cleaned it up to using 2 spaces (thus the conflicts you see now). Also there's a maven checkstyle plugin in place now that will throw failure at build time when the style is not adequate. Please try to fix this two items and let me know when you'll be ready to proceed with peer review.

Thanks!

**Comment by FerUy** [comment]
Thanks @brainslog , I'll let you know when this work is ready for peer review.

**Comment by FerUy** [comment]
Previous commit c5187a5 applies for issues #37 and #38. PR #48.

**Comment by FerUy** [comment]
@brainslog in the last commit (it was me, I had the email bad set in Source Tree, don't know why, but apparently yesterday I messed up with the configuration there as cloned again from there for fixing other issue, already corrected though) I reverted a needed change for not making the PR conflict with master, but I believe there's a mistake there with **Location-Estimate** AVP.

Either in 3GPP TS 29.172 (SLg) as in 3GPP TS 32.299 (where it is specified) it is defined as OctetString. Here the extract from 3GPP TS 32.299 (last release, 14.1.0)

7.2.94	Location-Estimate AVP
The Location-Estimate AVP (AVP code 1242) is of type **OctetString** and contains an estimate of the location of an MS in universal coordinates and the accuracy of the estimate. Refers to the geographical area description in TS 23.032 [227] for the internal structure and encoding of this AVP.

The problem is that in master dictionary.xml it's defined as UTF8String (including testsuite one):

`<avpdefn name="Location-Estimate" code="1242" vendor-id="TGPP" mandatory="must" protected="may" may-encrypt="no" vendor-bit="must" >
    <type type-name="UTF8String" />
  </avpdefn>`

I could revert the implementation of that AVP to UTF8String, but ultimately it's not how it will work. Wdyt? Am I wright? If so, could you please fix that so I could continue without conflicting?
This work is almost ready, but need to define what to do with that AVP asap.

Thanks in advance

**Comment by FerUy** [comment]
All Junit tests passing. Attached console logs (all AVPs included as for both 3GPP TS 29.172 and 29.173).
Only thing remaining, is changing Location-Estimate AVP in dictionary to OctetString as in PR #62:

`<avpdefn name="Location-Estimate" code="1242" vendor-id="TGPP" mandatory="must" protected="may" may-encrypt="no" vendor-bit="must" >
    <type type-name="OctetString" /> 
  </avpdefn>`

[SLh_junit_test_RIR-RIA_OK.txt](https://github.com/RestComm/jdiameter/files/543373/SLh_junit_test_RIR-RIA_OK.txt)
[SLg_junit_test_PLR-PLA_OK.txt](https://github.com/RestComm/jdiameter/files/543374/SLg_junit_test_PLR-PLA_OK.txt)
[SLg_junit_test_LRR-LRA_OK.txt](https://github.com/RestComm/jdiameter/files/543375/SLg_junit_test_LRR-LRA_OK.txt)

**Comment by FerUy** [comment]
@brainslog, work on this is finished. All yours to push the green button ;)

**Comment by FerUy** [comment]
With latest version of Wireshark and by adding all AVP definitions in dictionary.xml (of Wireshark, as it does not contain all as defined in 3GPP TS 29.172 and 29.173 but a subset), the attached traces are obtainable (you need to add TCP ports 13868 and 4868 in Wireshark preferences->protocols-Diameter). All AVPs are obviously filled with random but acceptable values. 
[SLg-SLh_Testuite_Wireshark-Traces.zip](https://github.com/RestComm/jdiameter/files/638408/SLg-SLh_Testuite_Wireshark-Traces.zip)

**Comment by FerUy** [comment]
With latest version of Wireshark (2.2.3) and by adding all AVP definitions in Wireshark's Diameter dictionary.xml, the attached traces are obtainable, with all AVPs properly populated as for either SLh and SLg specs after running Junit tests (you also need to add TCP ports 13868 and 4868 in Wireshark preferences->protocols-Diameter for this purpose). 

All AVPs are filled with random but acceptable values. Wireshark's improved dictionary.xml, with AVPs for 3GPP TS 29.172 needed additions, is also attached (latest version only contains a subset of AVPs defined in 3GPP TS 29.172 and 29.173).

[SLh-SLg_JunitTest_Traces_&_Wireshark_diameter_dictionary.zip](https://github.com/RestComm/jdiameter/files/665009/SLh-SLg_JunitTest_Traces_._Wireshark_diameter_dictionary.zip)

**Comment by FerUy** [comment]
Closing this PR, which is replaced by PR #111.

**Pull request closed without merging**
