### PR TITLE
Fix for issue#78 - AVP index getters and fix for insert AVP with index

### PR DESCRIPTION
**Pull request by gfigiel**
New getters implemented and fix for insert AVP.

### CODE REVIEW

**Comment by gfigiel** [comment]
Please review the changes and merge with master.

**Comment by deruelle** [comment]
Thanks @gfigiel. @brainslog please review

**Comment by bkrok** [comment]
The code has been reformatted.

**Comment by brainslog** [comment]
Thanks! Merged, but there was still a checkstyle issue at https://github.com/RestComm/jdiameter/pull/79/files#diff-665366009e893fcf4848addce3c2cefdR243, it is shown when trying to build with maven:

```
...
[INFO] --- maven-checkstyle-plugin:2.17:check (check) @ jdiameter-impl ---
[INFO] Starting audit...
[ERROR] /jdiameter/core/jdiameter/impl/src/main/java/org/jdiameter/client/impl/parser/AvpSetImpl.java:243: 'method def' child have incorrect indentation level 8, expected level should be 4. [Indentation]
Audit done.
...
```

It has been fixed separately.

**Pull request merged**
